apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      nginx-1'
  creationTimestamp: "2020-10-05T20:05:15Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2020-10-05T20:11:06Z"
  generateName: nginx-1-76949974bb-
  labels:
    app: nginx-1
    pod-template-hash: 76949974bb
  name: nginx-1-76949974bb-r5vhb
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-1-76949974bb
    uid: 338fa162-7150-4427-baeb-65e41c99271c
  resourceVersion: "4875"
  selfLink: /api/v1/namespaces/default/pods/nginx-1-76949974bb-r5vhb
  uid: f89682ab-6e14-41a6-911d-92b5d6ce1618
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-1
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-p5f88
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-standard-cluster-1-default-pool-72144d15-zhww
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-p5f88
    secret:
      defaultMode: 420
      secretName: default-token-p5f88
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:05:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:10:37Z"
    message: 'containers with unready status: [nginx-1]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:10:37Z"
    message: 'containers with unready status: [nginx-1]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:05:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6285739d1476226ad4bd71a4ca0921cfa6148f2117886d496146d3ac20c0379d
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:794275d96b4ab96eeb954728a7bf11156570e8372ecd5ed0cbc7280313a27d19
    lastState: {}
    name: nginx-1
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://6285739d1476226ad4bd71a4ca0921cfa6148f2117886d496146d3ac20c0379d
        exitCode: 0
        finishedAt: "2020-10-05T20:10:36Z"
        reason: Completed
        startedAt: "2020-10-05T20:05:21Z"
  hostIP: 10.128.0.5
  phase: Running
  podIP: 10.8.3.2
  qosClass: Burstable
  startTime: "2020-10-05T20:05:15Z"
