apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      nginx-1'
  creationTimestamp: "2020-10-05T20:05:14Z"
  generateName: nginx-1-76949974bb-
  labels:
    app: nginx-1
    pod-template-hash: 76949974bb
  name: nginx-1-76949974bb-ft9s4
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-1-76949974bb
    uid: 338fa162-7150-4427-baeb-65e41c99271c
  resourceVersion: "3427"
  selfLink: /api/v1/namespaces/default/pods/nginx-1-76949974bb-ft9s4
  uid: f02a0107-fdcf-4909-8ac1-67a4ffddaf18
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-1
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-p5f88
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-standard-cluster-1-default-pool-72144d15-zhww
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-p5f88
    secret:
      defaultMode: 420
      secretName: default-token-p5f88
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:05:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:05:21Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:05:21Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-10-05T20:05:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2a11630aa007fd301f93836aaff2534f1bb167d1e5ce0e8806c53ec4d8bb0e00
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:794275d96b4ab96eeb954728a7bf11156570e8372ecd5ed0cbc7280313a27d19
    lastState: {}
    name: nginx-1
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-10-05T20:05:21Z"
  hostIP: 10.128.0.5
  phase: Running
  podIP: 10.8.3.3
  qosClass: Burstable
  startTime: "2020-10-05T20:05:15Z"
